logging:
  config: classpath:logback-uat.xml

spring:
  mail:
    host: smtp.spreadtrum.com
    port: 587
    username: CRM.Admin@UniSoC.com
    password: caCA$617
    protocol: smtp
    default-encoding: UTF-8

  datasource:
    username: crmportalqa
    password: Crm$20%My99
    url: jdbc:mysql://10.29.60.170:3306/crmportalqa?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver