server:
  port: 9090
  servlet:
    context-path: /portal-task

camel:
    springboot:
        main-run-controller: true

spring:
    batch:
        initializer:
            enabled: false
        job:
            enabled: false
    main:
        allow-bean-definition-overriding: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat,wall,slf4j
        initialSize: 10
        minIdle: 5
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties:
          druid:
            stat:
              mergeSql: true
              slowSqlMillis: 5000
    profiles:
        active: dev
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        encoding: UTF-8
        mode: HTML5

login:
    password: 1234
    username: admin