logging:
  config: classpath:logback-sit.xml

camel:
    springboot:
        main-run-controller: true

spring:
  mail:
    host: smtp.qq.com
    username: biao.chenit@qq.com
    password: ewennkedjtdebeca
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username}


  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
